//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUDGETModule.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BUDGETModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статья бюджета.
        /// </summary>
        public static string fBudgetItem {
            get {
                return ResourceManager.GetString("fBudgetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статьи бюджета.
        /// </summary>
        public static string fBudgetItems {
            get {
                return ResourceManager.GetString("fBudgetItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планирование бюджета.
        /// </summary>
        public static string fBudgetPlanning {
            get {
                return ResourceManager.GetString("fBudgetPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта.
        /// </summary>
        public static string fCurrency {
            get {
                return ResourceManager.GetString("fCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планирование по статье.
        /// </summary>
        public static string fPlanningBudgetItem {
            get {
                return ResourceManager.GetString("fPlanningBudgetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Судовладельцы.
        /// </summary>
        public static string fShipowners {
            get {
                return ResourceManager.GetString("fShipowners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставщик.
        /// </summary>
        public static string fSupplier {
            get {
                return ResourceManager.GetString("fSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставщики.
        /// </summary>
        public static string fSuppliers {
            get {
                return ResourceManager.GetString("fSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string txtAddress {
            get {
                return ResourceManager.GetString("txtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Апрель по факту.
        /// </summary>
        public static string txtAprilA {
            get {
                return ResourceManager.GetString("txtAprilA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Август по факту.
        /// </summary>
        public static string txtAugustA {
            get {
                return ResourceManager.GetString("txtAugustA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исполнение бюджета.
        /// </summary>
        public static string txtBudgetActual {
            get {
                return ResourceManager.GetString("txtBudgetActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код бюджета.
        /// </summary>
        public static string txtBudgetCode {
            get {
                return ResourceManager.GetString("txtBudgetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бюджет компании.
        /// </summary>
        public static string txtBudgetCompany {
            get {
                return ResourceManager.GetString("txtBudgetCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Используется в бюджете компании.
        /// </summary>
        public static string txtBudgetCompanyCheckBox {
            get {
                return ResourceManager.GetString("txtBudgetCompanyCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта бюджета.
        /// </summary>
        public static string txtBudgetCurrency {
            get {
                return ResourceManager.GetString("txtBudgetCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бюджет флота.
        /// </summary>
        public static string txtBudgetFleet {
            get {
                return ResourceManager.GetString("txtBudgetFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статья бюджета.
        /// </summary>
        public static string txtBudgetItem {
            get {
                return ResourceManager.GetString("txtBudgetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планирование бюджета.
        /// </summary>
        public static string txtBudgetPlanning {
            get {
                return ResourceManager.GetString("txtBudgetPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string txtCode {
            get {
                return ResourceManager.GetString("txtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добросовестные поставщики.
        /// </summary>
        public static string txtConscientiousSuppliers {
            get {
                return ResourceManager.GetString("txtConscientiousSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактное лицо.
        /// </summary>
        public static string txtContactPerson {
            get {
                return ResourceManager.GetString("txtContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статья будет скопирована для выбраного судовладельца вместе с подстатьями..
        /// </summary>
        public static string txtCopyBudgetItem {
            get {
                return ResourceManager.GetString("txtCopyBudgetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Валюта.
        /// </summary>
        public static string txtCurrencyCode {
            get {
                return ResourceManager.GetString("txtCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название валюты.
        /// </summary>
        public static string txtCurrencyName {
            get {
                return ResourceManager.GetString("txtCurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декабрь по факту.
        /// </summary>
        public static string txtDecemberA {
            get {
                return ResourceManager.GetString("txtDecemberA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название (русский).
        /// </summary>
        public static string txtDescription {
            get {
                return ResourceManager.GetString("txtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название (английский).
        /// </summary>
        public static string txtDescriptionEng {
            get {
                return ResourceManager.GetString("txtDescriptionEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначение.
        /// </summary>
        public static string txtDesсriptionUse {
            get {
                return ResourceManager.GetString("txtDesсriptionUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отклонение  (USD).
        /// </summary>
        public static string txtDeviationInBaseCurrency {
            get {
                return ResourceManager.GetString("txtDeviationInBaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отклонение (%).
        /// </summary>
        public static string txtDeviationPercent {
            get {
                return ResourceManager.GetString("txtDeviationPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Февраль по факту.
        /// </summary>
        public static string txtFebruaryA {
            get {
                return ResourceManager.GetString("txtFebruaryA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файлы.
        /// </summary>
        public static string txtFiles {
            get {
                return ResourceManager.GetString("txtFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Групповая статья.
        /// </summary>
        public static string txtGroupItem {
            get {
                return ResourceManager.GetString("txtGroupItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В бюджете (по умолчанию).
        /// </summary>
        public static string txtInBudgetTable {
            get {
                return ResourceManager.GetString("txtInBudgetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реестр счетов.
        /// </summary>
        public static string txtInvoicesRegistry {
            get {
                return ResourceManager.GetString("txtInvoicesRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статья.
        /// </summary>
        public static string txtItem {
            get {
                return ResourceManager.GetString("txtItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итог по статье.
        /// </summary>
        public static string txtItemTotal {
            get {
                return ResourceManager.GetString("txtItemTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактический итог по статье.
        /// </summary>
        public static string txtItemTotalActual {
            get {
                return ResourceManager.GetString("txtItemTotalActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Январь по факту.
        /// </summary>
        public static string txtJanuaryA {
            get {
                return ResourceManager.GetString("txtJanuaryA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июль по факту.
        /// </summary>
        public static string txtJulyA {
            get {
                return ResourceManager.GetString("txtJulyA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июнь по факту.
        /// </summary>
        public static string txtJuneA {
            get {
                return ResourceManager.GetString("txtJuneA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Март по факту.
        /// </summary>
        public static string txtMarchA {
            get {
                return ResourceManager.GetString("txtMarchA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Май по факту.
        /// </summary>
        public static string txtMayA {
            get {
                return ResourceManager.GetString("txtMayA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбрана базовая валюта.
        /// </summary>
        public static string txtNoBaseCurrency {
            get {
                return ResourceManager.GetString("txtNoBaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недобросовестный поставщик.
        /// </summary>
        public static string txtNotConscientiousSuppliers {
            get {
                return ResourceManager.GetString("txtNotConscientiousSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноябрь по факту.
        /// </summary>
        public static string txtNovemberA {
            get {
                return ResourceManager.GetString("txtNovemberA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Октябрь по факту.
        /// </summary>
        public static string txtOctoberA {
            get {
                return ResourceManager.GetString("txtOctoberA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входит в состав статьи.
        /// </summary>
        public static string txtParentArticle {
            get {
                return ResourceManager.GetString("txtParentArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string txtPhone {
            get {
                return ResourceManager.GetString("txtPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квартал.
        /// </summary>
        public static string txtQuarter {
            get {
                return ResourceManager.GetString("txtQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квартал по факту.
        /// </summary>
        public static string txtQuarterActual {
            get {
                return ResourceManager.GetString("txtQuarterActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация квитанций.
        /// </summary>
        public static string txtReceiptsRegistre {
            get {
                return ResourceManager.GetString("txtReceiptsRegistre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сентябрь по факту.
        /// </summary>
        public static string txtSeptemberA {
            get {
                return ResourceManager.GetString("txtSeptemberA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string txtShipownerName {
            get {
                return ResourceManager.GetString("txtShipownerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Судовладельцы.
        /// </summary>
        public static string txtShipowners {
            get {
                return ResourceManager.GetString("txtShipowners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Детализация.
        /// </summary>
        public static string txtSpecification {
            get {
                return ResourceManager.GetString("txtSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставщик.
        /// </summary>
        public static string txtSupplier {
            get {
                return ResourceManager.GetString("txtSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string txtSupplierName {
            get {
                return ResourceManager.GetString("txtSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого:.
        /// </summary>
        public static string txtTotal {
            get {
                return ResourceManager.GetString("txtTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого фактически:.
        /// </summary>
        public static string txtTotalFact {
            get {
                return ResourceManager.GetString("txtTotalFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость (USD).
        /// </summary>
        public static string txtValueInBaseCurrency {
            get {
                return ResourceManager.GetString("txtValueInBaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НДС.
        /// </summary>
        public static string txtVAT {
            get {
                return ResourceManager.GetString("txtVAT", resourceCulture);
            }
        }
    }
}
