//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        public static string fAuthorization {
            get {
                return ResourceManager.GetString("fAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страны.
        /// </summary>
        public static string fCountries {
            get {
                return ResourceManager.GetString("fCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники.
        /// </summary>
        public static string fDirectories {
            get {
                return ResourceManager.GetString("fDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string fUser {
            get {
                return ResourceManager.GetString("fUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить данную страну, так как эта страна уже используется!.
        /// </summary>
        public static string mCantDelUsedCountry {
            get {
                return ResourceManager.GetString("mCantDelUsedCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить?.
        /// </summary>
        public static string mConfirmDel {
            get {
                return ResourceManager.GetString("mConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить страну?.
        /// </summary>
        public static string mConfirmDelCountry {
            get {
                return ResourceManager.GetString("mConfirmDelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить файл?.
        /// </summary>
        public static string mConfirmDelFile {
            get {
                return ResourceManager.GetString("mConfirmDelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить ответственного?.
        /// </summary>
        public static string mConfirmDelResponsible {
            get {
                return ResourceManager.GetString("mConfirmDelResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить данное свойство?.
        /// </summary>
        public static string mConfirmDelShipProperty {
            get {
                return ResourceManager.GetString("mConfirmDelShipProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить пользователя?.
        /// </summary>
        public static string mConfirmDelUser {
            get {
                return ResourceManager.GetString("mConfirmDelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль!.
        /// </summary>
        public static string mErInvalidLogOrPsw {
            get {
                return ResourceManager.GetString("mErInvalidLogOrPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким логином уже существует! Введите уникальный логин!.
        /// </summary>
        public static string mErNotUniqueLogin {
            get {
                return ResourceManager.GetString("mErNotUniqueLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим &quot;Разметка страницы&quot; недоступен. Для предпросмотра используйте экспорт в PDF..
        /// </summary>
        public static string mPageLayoutEr {
            get {
                return ResourceManager.GetString("mPageLayoutEr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить ответственного, так как у этого ответственного есть назначенные ему замечания!.
        /// </summary>
        public static string mResponsibleHasObservations {
            get {
                return ResourceManager.GetString("mResponsibleHasObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ.
        /// </summary>
        public static string rAnswer {
            get {
                return ResourceManager.GetString("rAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аудит.
        /// </summary>
        public static string rAudit {
            get {
                return ResourceManager.GetString("rAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднее количество замечаний.
        /// </summary>
        public static string rAvgObsInInspection {
            get {
                return ResourceManager.GetString("rAvgObsInInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднее значение замечаний по флоту.
        /// </summary>
        public static string rAvgObsTitle {
            get {
                return ResourceManager.GetString("rAvgObsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лучшая практика.
        /// </summary>
        public static string rBPI {
            get {
                return ResourceManager.GetString("rBPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания.
        /// </summary>
        public static string rByCompany {
            get {
                return ResourceManager.GetString("rByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Судно.
        /// </summary>
        public static string rByVessel {
            get {
                return ResourceManager.GetString("rByVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раздел.
        /// </summary>
        public static string rChapter {
            get {
                return ResourceManager.GetString("rChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раздел не указан.
        /// </summary>
        public static string rChapterNotSpecified {
            get {
                return ResourceManager.GetString("rChapterNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата закрытия.
        /// </summary>
        public static string rClosedDate {
            get {
                return ResourceManager.GetString("rClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество закрытых замечаний.
        /// </summary>
        public static string rClosedObsCount {
            get {
                return ResourceManager.GetString("rClosedObsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устранить до.
        /// </summary>
        public static string rClosedTillDate {
            get {
                return ResourceManager.GetString("rClosedTillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии.
        /// </summary>
        public static string rComments {
            get {
                return ResourceManager.GetString("rComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания.
        /// </summary>
        public static string rCompany {
            get {
                return ResourceManager.GetString("rCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сравнение результатов инспекций.
        /// </summary>
        public static string rComparisonOfInspectionResults {
            get {
                return ResourceManager.GetString("rComparisonOfInspectionResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отметка об устранении (подпись).
        /// </summary>
        public static string rConfirmation {
            get {
                return ResourceManager.GetString("rConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копии отчета переданы.
        /// </summary>
        public static string rCopiesReport {
            get {
                return ResourceManager.GetString("rCopiesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корректирующее действие.
        /// </summary>
        public static string rCorrectiveActions {
            get {
                return ResourceManager.GetString("rCorrectiveActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CRITICAL.
        /// </summary>
        public static string rCritical {
            get {
                return ResourceManager.GetString("rCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string rDate {
            get {
                return ResourceManager.GetString("rDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата (дд.мм.гггг).
        /// </summary>
        public static string rDateDDMMYYYY {
            get {
                return ResourceManager.GetString("rDateDDMMYYYY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название подразделения.
        /// </summary>
        public static string rDepartment {
            get {
                return ResourceManager.GetString("rDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактическая дата.
        /// </summary>
        public static string rFactDate {
            get {
                return ResourceManager.GetString("rFactDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Флот.
        /// </summary>
        public static string rFleet {
            get {
                return ResourceManager.GetString("rFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IMO/VIN.
        /// </summary>
        public static string rImoVinReg {
            get {
                return ResourceManager.GetString("rImoVinReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инспекция.
        /// </summary>
        public static string rInspection {
            get {
                return ResourceManager.GetString("rInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество инспекций.
        /// </summary>
        public static string rInspectionCount {
            get {
                return ResourceManager.GetString("rInspectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет по инспекции.
        /// </summary>
        public static string rInspectionReport {
            get {
                return ResourceManager.GetString("rInspectionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акт инспекции.
        /// </summary>
        public static string rInspectionReportLukoil {
            get {
                return ResourceManager.GetString("rInspectionReportLukoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История инспекций.
        /// </summary>
        public static string rInspectionsHistory {
            get {
                return ResourceManager.GetString("rInspectionsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инспектор.
        /// </summary>
        public static string rInspector {
            get {
                return ResourceManager.GetString("rInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечания инспектора.
        /// </summary>
        public static string rInspectorObservations {
            get {
                return ResourceManager.GetString("rInspectorObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет аудита компании.
        /// </summary>
        public static string rInternalAuditReport {
            get {
                return ResourceManager.GetString("rInternalAuditReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание работы.
        /// </summary>
        public static string rJobDescription {
            get {
                return ResourceManager.GetString("rJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ссылка на инструкцию.
        /// </summary>
        public static string rJobInstructionRef {
            get {
                return ResourceManager.GetString("rJobInstructionRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на План работ.
        /// </summary>
        public static string rJobPlanning {
            get {
                return ResourceManager.GetString("rJobPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Капитан.
        /// </summary>
        public static string rMaster {
            get {
                return ResourceManager.GetString("rMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность, группа судов и район плавания по диплому для ВВП, дата окончания.
        /// </summary>
        public static string rMatrixAreal {
            get {
                return ResourceManager.GetString("rMatrixAreal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид морского диплома (ПДМНВ), дата окончания.
        /// </summary>
        public static string rMatrixDiplom {
            get {
                return ResourceManager.GetString("rMatrixDiplom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность.
        /// </summary>
        public static string rMatrixRank {
            get {
                return ResourceManager.GetString("rMatrixRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Танкерная сертификация / противопожарная подготовка.
        /// </summary>
        public static string rMatrixSertification {
            get {
                return ResourceManager.GetString("rMatrixSertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество лет работы в данной должности.
        /// </summary>
        public static string rMatrixYearsInRank {
            get {
                return ResourceManager.GetString("rMatrixYearsInRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество лет работы с данным оператором.
        /// </summary>
        public static string rMatrixYearsOperator {
            get {
                return ResourceManager.GetString("rMatrixYearsOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключевые вопросы отмеченные НП без комментариев.
        /// </summary>
        public static string rNaWithoutComm {
            get {
                return ResourceManager.GetString("rNaWithoutComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет записей.
        /// </summary>
        public static string rNoRecords {
            get {
                return ResourceManager.GetString("rNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключевые вопросы отмеченные НВ без комментариев и без замечаний.
        /// </summary>
        public static string rNsWithoutComm {
            get {
                return ResourceManager.GetString("rNsWithoutComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект.
        /// </summary>
        public static string rObject {
            get {
                return ResourceManager.GetString("rObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечания и корректирующие действия.
        /// </summary>
        public static string rObsAndCorrActions {
            get {
                return ResourceManager.GetString("rObsAndCorrActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество замечаний.
        /// </summary>
        public static string rObsCount {
            get {
                return ResourceManager.GetString("rObsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечание.
        /// </summary>
        public static string rObservation {
            get {
                return ResourceManager.GetString("rObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список замечаний.
        /// </summary>
        public static string rObservationList {
            get {
                return ResourceManager.GetString("rObservationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип замечания.
        /// </summary>
        public static string rObservationType {
            get {
                return ResourceManager.GetString("rObservationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечания, записанные ниже, не следует рассматривать как детальный список. .
        /// </summary>
        public static string rObsListComment {
            get {
                return ResourceManager.GetString("rObsListComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечания указанные выше были обсуждены и согласованы с капитаном..
        /// </summary>
        public static string rObsListCommentM {
            get {
                return ResourceManager.GetString("rObsListCommentM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечания указанные выше были обсуждены и согласованы с ответственным лицом..
        /// </summary>
        public static string rObsListCommentRP {
            get {
                return ResourceManager.GetString("rObsListCommentRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечаний к компании.
        /// </summary>
        public static string rObsToCompany {
            get {
                return ResourceManager.GetString("rObsToCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечаний к экипажу.
        /// </summary>
        public static string rObsToCrew {
            get {
                return ResourceManager.GetString("rObsToCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор.
        /// </summary>
        public static string rOperator {
            get {
                return ResourceManager.GetString("rOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии оператора.
        /// </summary>
        public static string rOperComments {
            get {
                return ResourceManager.GetString("rOperComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невыполненные инспекции.
        /// </summary>
        public static string rOutstandingInspections {
            get {
                return ResourceManager.GetString("rOutstandingInspections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период.
        /// </summary>
        public static string rPeriod {
            get {
                return ResourceManager.GetString("rPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Процент закрытых замечаний.
        /// </summary>
        public static string rPersentClosedObs {
            get {
                return ResourceManager.GetString("rPersentClosedObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственное лицо.
        /// </summary>
        public static string rPIC {
            get {
                return ResourceManager.GetString("rPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственное лицо не указано.
        /// </summary>
        public static string rPICNotSpecified {
            get {
                return ResourceManager.GetString("rPICNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место аудита.
        /// </summary>
        public static string rPlaceOfAudit {
            get {
                return ResourceManager.GetString("rPlaceOfAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Планируемая дата.
        /// </summary>
        public static string rPlanDate {
            get {
                return ResourceManager.GetString("rPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт.
        /// </summary>
        public static string rPort {
            get {
                return ResourceManager.GetString("rPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждающее действие.
        /// </summary>
        public static string rPreventiveActions {
            get {
                return ResourceManager.GetString("rPreventiveActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос.
        /// </summary>
        public static string rQuestion {
            get {
                return ResourceManager.GetString("rQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопросник.
        /// </summary>
        public static string rQuestionnaire {
            get {
                return ResourceManager.GetString("rQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настоящий отчет составлен на основании последней редакции &quot;{0}&quot; и может использоваться только в интересах {1}.
        /// </summary>
        public static string rQuestionnaireRepInfo {
            get {
                return ResourceManager.GetString("rQuestionnaireRepInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не отвеченные вопросы.
        /// </summary>
        public static string rQuestionsWithoutAns {
            get {
                return ResourceManager.GetString("rQuestionsWithoutAns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string rRemark {
            get {
                return ResourceManager.GetString("rRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требующие внимания инспекции.
        /// </summary>
        public static string rRequireAttentionInspections {
            get {
                return ResourceManager.GetString("rRequireAttentionInspections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственный.
        /// </summary>
        public static string rResponsible {
            get {
                return ResourceManager.GetString("rResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственный (Компания).
        /// </summary>
        public static string rResponsibleCompany {
            get {
                return ResourceManager.GetString("rResponsibleCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственный.
        /// </summary>
        public static string rResponsiblePerson {
            get {
                return ResourceManager.GetString("rResponsiblePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственный (Судно).
        /// </summary>
        public static string rResponsibleVessel {
            get {
                return ResourceManager.GetString("rResponsibleVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат.
        /// </summary>
        public static string rResult {
            get {
                return ResourceManager.GetString("rResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень риска.
        /// </summary>
        public static string rRiskLevel {
            get {
                return ResourceManager.GetString("rRiskLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина.
        /// </summary>
        public static string rRootCause {
            get {
                return ResourceManager.GetString("rRootCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запланированные инспекции.
        /// </summary>
        public static string rScheduledInspections {
            get {
                return ResourceManager.GetString("rScheduledInspections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Секция {0}.
        /// </summary>
        public static string rSection {
            get {
                return ResourceManager.GetString("rSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчет инспекции судна.
        /// </summary>
        public static string rShipInspectionReport {
            get {
                return ResourceManager.GetString("rShipInspectionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подпись.
        /// </summary>
        public static string rSignature {
            get {
                return ResourceManager.GetString("rSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string rStatus {
            get {
                return ResourceManager.GetString("rStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего.
        /// </summary>
        public static string rTotal {
            get {
                return ResourceManager.GetString("rTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего замечаний.
        /// </summary>
        public static string rTotalObs {
            get {
                return ResourceManager.GetString("rTotalObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего закрытых замечаний.
        /// </summary>
        public static string rTotalObsClosed {
            get {
                return ResourceManager.GetString("rTotalObsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип не определен.
        /// </summary>
        public static string rTypeNotSpecified {
            get {
                return ResourceManager.GetString("rTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название судна.
        /// </summary>
        public static string rVesselName {
            get {
                return ResourceManager.GetString("rVesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключевые вопросы отмеченные ДА без комментариев.
        /// </summary>
        public static string rYesWithoutComm {
            get {
                return ResourceManager.GetString("rYesWithoutComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступны все разделы.
        /// </summary>
        public static string txtAccessAllPartitions {
            get {
                return ResourceManager.GetString("txtAccessAllPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступны некоторые разделы.
        /// </summary>
        public static string txtAccessSomePartitions {
            get {
                return ResourceManager.GetString("txtAccessSomePartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ к разделам.
        /// </summary>
        public static string txtAccessToPartitions {
            get {
                return ResourceManager.GetString("txtAccessToPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная информация.
        /// </summary>
        public static string txtAdditionalProperties {
            get {
                return ResourceManager.GetString("txtAdditionalProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительное свойство.
        /// </summary>
        public static string txtAdditionalProperty {
            get {
                return ResourceManager.GetString("txtAdditionalProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные.
        /// </summary>
        public static string txtAdditionalPropertyData {
            get {
                return ResourceManager.GetString("txtAdditionalPropertyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string txtAdditionalPropertyDescription {
            get {
                return ResourceManager.GetString("txtAdditionalPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название свойства.
        /// </summary>
        public static string txtAdditionalPropertyName {
            get {
                return ResourceManager.GetString("txtAdditionalPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Позывной сигнал.
        /// </summary>
        public static string txtCallSign {
            get {
                return ResourceManager.GetString("txtCallSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создано компанией:.
        /// </summary>
        public static string txtCreatedByCompany {
            get {
                return ResourceManager.GetString("txtCreatedByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на д..
        /// </summary>
        public static string txtD {
            get {
                return ResourceManager.GetString("txtD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменено компанией:.
        /// </summary>
        public static string txtEditedByCompany {
            get {
                return ResourceManager.GetString("txtEditedByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать личные данные.
        /// </summary>
        public static string txtEditPersonalData {
            get {
                return ResourceManager.GetString("txtEditPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на e-mail.
        /// </summary>
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string txtEnter {
            get {
                return ResourceManager.GetString("txtEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести не менее {0}..
        /// </summary>
        public static string txtEnterComplexNumberValueNotLess {
            get {
                return ResourceManager.GetString("txtEnterComplexNumberValueNotLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести не более {0}..
        /// </summary>
        public static string txtEnterComplexNumberValueNotMore {
            get {
                return ResourceManager.GetString("txtEnterComplexNumberValueNotMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести число отличное от нуля..
        /// </summary>
        public static string txtEnterComplexNumberValueNotZero {
            get {
                return ResourceManager.GetString("txtEnterComplexNumberValueNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из.
        /// </summary>
        public static string txtFrom {
            get {
                return ResourceManager.GetString("txtFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить справочник &quot;Типы топлива&quot;.
        /// </summary>
        public static string txtFuelTypeDictionaryIsEmpty {
            get {
                return ResourceManager.GetString("txtFuelTypeDictionaryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактор выброса 
        ///(т. CO2/ т. топлива).
        /// </summary>
        public static string txtFuelTypeEmissionFactor {
            get {
                return ResourceManager.GetString("txtFuelTypeEmissionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите типы топлива, которые используются на судне.
        /// </summary>
        public static string txtFuelTypeIsUseOnShip {
            get {
                return ResourceManager.GetString("txtFuelTypeIsUseOnShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Типы топлива, которые используются на судне.
        /// </summary>
        public static string txtFuelTypeIsUseOnShipView {
            get {
                return ResourceManager.GetString("txtFuelTypeIsUseOnShipView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип топлива.
        /// </summary>
        public static string txtFuelTypeName {
            get {
                return ResourceManager.GetString("txtFuelTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Короткое наименование.
        /// </summary>
        public static string txtFuelTypeShortName {
            get {
                return ResourceManager.GetString("txtFuelTypeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные инспектора.
        /// </summary>
        public static string txtInspectorData {
            get {
                return ResourceManager.GetString("txtInspectorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О. инспектора.
        /// </summary>
        public static string txtInspectorFIO {
            get {
                return ResourceManager.GetString("txtInspectorFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная информация.
        /// </summary>
        public static string txtInspectorInfo {
            get {
                return ResourceManager.GetString("txtInspectorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID инспектора.
        /// </summary>
        public static string txtInspectorNum {
            get {
                return ResourceManager.GetString("txtInspectorNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата постройки.
        /// </summary>
        public static string txtIssueDate {
            get {
                return ResourceManager.GetString("txtIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата обновления:.
        /// </summary>
        public static string txtLastDateRefresh {
            get {
                return ResourceManager.GetString("txtLastDateRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последний экспорт:.
        /// </summary>
        public static string txtLastExport {
            get {
                return ResourceManager.GetString("txtLastExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последний импорт:.
        /// </summary>
        public static string txtLastImport {
            get {
                return ResourceManager.GetString("txtLastImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход из системы.
        /// </summary>
        public static string txtLogOut {
            get {
                return ResourceManager.GetString("txtLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м..
        /// </summary>
        public static string txtM {
            get {
                return ResourceManager.GetString("txtM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные сведения о судне.
        /// </summary>
        public static string txtMainVesselData {
            get {
                return ResourceManager.GetString("txtMainVesselData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление инспекторами.
        /// </summary>
        public static string txtManagementOfInspectors {
            get {
                return ResourceManager.GetString("txtManagementOfInspectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация об изменениях.
        /// </summary>
        public static string txtModifyInfo {
            get {
                return ResourceManager.GetString("txtModifyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход не выполнен.
        /// </summary>
        public static string txtNotLoggedIn {
            get {
                return ResourceManager.GetString("txtNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записей на странице:.
        /// </summary>
        public static string txtNumRecordsPerPage {
            get {
                return ResourceManager.GetString("txtNumRecordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер пакета.
        /// </summary>
        public static string txtPackageNumber {
            get {
                return ResourceManager.GetString("txtPackageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страница.
        /// </summary>
        public static string txtPage {
            get {
                return ResourceManager.GetString("txtPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string txtPass {
            get {
                return ResourceManager.GetString("txtPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите пароль.
        /// </summary>
        public static string txtPassRepeat {
            get {
                return ResourceManager.GetString("txtPassRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работник.
        /// </summary>
        public static string txtPerson {
            get {
                return ResourceManager.GetString("txtPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Префикс для заявок.
        /// </summary>
        public static string txtPrefixRequistion {
            get {
                return ResourceManager.GetString("txtPrefixRequistion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Префикс используется для формирования номера заявки, создаваемой судном. В префиксе можно использовать разделительные символы (- или /). Например, если указан префикс «ABC-», то номер заявки будет выглядеть следующим образом: «ABC-253/2016-05-25»..
        /// </summary>
        public static string txtPrefixRequistionDescription {
            get {
                return ResourceManager.GetString("txtPrefixRequistionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование.
        /// </summary>
        public static string txtRefBookName {
            get {
                return ResourceManager.GetString("txtRefBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить все данные.
        /// </summary>
        public static string txtRefresh {
            get {
                return ResourceManager.GetString("txtRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственный.
        /// </summary>
        public static string txtResponsible {
            get {
                return ResourceManager.GetString("txtResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные ответственного.
        /// </summary>
        public static string txtResponsibleData {
            get {
                return ResourceManager.GetString("txtResponsibleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О. ответственного.
        /// </summary>
        public static string txtResponsibleFIO {
            get {
                return ResourceManager.GetString("txtResponsibleFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность.
        /// </summary>
        public static string txtResponsiblePost {
            get {
                return ResourceManager.GetString("txtResponsiblePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответственные.
        /// </summary>
        public static string txtResponsibles {
            get {
                return ResourceManager.GetString("txtResponsibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string txtRoleAdmin {
            get {
                return ResourceManager.GetString("txtRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление справочниками
        ///Управление пользователями
        ///Загрузка данных из 1С.
        /// </summary>
        public static string txtRoleAdminInfo {
            get {
                return ResourceManager.GetString("txtRoleAdminInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка вопросников.
        /// </summary>
        public static string txtRoleAdminInfo_IAA {
            get {
                return ResourceManager.GetString("txtRoleAdminInfo_IAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер инспекций компании.
        /// </summary>
        public static string txtRoleCompInsManager {
            get {
                return ResourceManager.GetString("txtRoleCompInsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление инспекциями компании.
        /// </summary>
        public static string txtRoleCompInsManagerInfo {
            get {
                return ResourceManager.GetString("txtRoleCompInsManagerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление пользователями.
        /// </summary>
        public static string txtRoleCrewHoursAdminInfo {
            get {
                return ResourceManager.GetString("txtRoleCrewHoursAdminInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступен обмен данными.
        /// </summary>
        public static string txtRoleEI {
            get {
                return ResourceManager.GetString("txtRoleEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер инспекций флота.
        /// </summary>
        public static string txtRoleFlotInsManager {
            get {
                return ResourceManager.GetString("txtRoleFlotInsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление инспекциями флота.
        /// </summary>
        public static string txtRoleFlotInsManagerInfo {
            get {
                return ResourceManager.GetString("txtRoleFlotInsManagerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инспектор.
        /// </summary>
        public static string txtRoleInspector {
            get {
                return ResourceManager.GetString("txtRoleInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление собственными инспекциями.
        /// </summary>
        public static string txtRoleInspectorInfo {
            get {
                return ResourceManager.GetString("txtRoleInspectorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер по работе с персоналом.
        /// </summary>
        public static string txtRolePMSPersonnelManager {
            get {
                return ResourceManager.GetString("txtRolePMSPersonnelManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание, редактирование объектов, работ, СЗЧ и т.д..
        /// </summary>
        public static string txtRolePMSShipCatalogueManagerInfo {
            get {
                return ResourceManager.GetString("txtRolePMSShipCatalogueManagerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер редактора шаблонов.
        /// </summary>
        public static string txtRolePMSTemplatesManager {
            get {
                return ResourceManager.GetString("txtRolePMSTemplatesManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание, редактирование шаблонов.
        /// </summary>
        public static string txtRolePMSTemplatesManagerInfo {
            get {
                return ResourceManager.GetString("txtRolePMSTemplatesManagerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роли.
        /// </summary>
        public static string txtRoles {
            get {
                return ResourceManager.GetString("txtRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить пароль.
        /// </summary>
        public static string txtSavePass {
            get {
                return ResourceManager.GetString("txtSavePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрано {0} из {1}.
        /// </summary>
        public static string txtSelectedOf {
            get {
                return ResourceManager.GetString("txtSelectedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для судна не выбрано ни одного типа топлива.
        /// </summary>
        public static string txtShipFuelTypeListIsEmpty {
            get {
                return ResourceManager.GetString("txtShipFuelTypeListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать информацию об изменениях записи.
        /// </summary>
        public static string txtShowChangeInfo {
            get {
                return ResourceManager.GetString("txtShowChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string txtTel {
            get {
                return ResourceManager.GetString("txtTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего записей:.
        /// </summary>
        public static string txtTotalRecords {
            get {
                return ResourceManager.GetString("txtTotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на д..
        /// </summary>
        public static string txtUnitD {
            get {
                return ResourceManager.GetString("txtUnitD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ч..
        /// </summary>
        public static string txtUnitH {
            get {
                return ResourceManager.GetString("txtUnitH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м..
        /// </summary>
        public static string txtUnitM {
            get {
                return ResourceManager.GetString("txtUnitM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Единицы груза.
        /// </summary>
        public static string txtUnitOfCargo {
            get {
                return ResourceManager.GetString("txtUnitOfCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание! Единицы груза изменятся во всех рейсах данного судна..
        /// </summary>
        public static string txtUnitOfCargoTextForUser {
            get {
                return ResourceManager.GetString("txtUnitOfCargoTextForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на с..
        /// </summary>
        public static string txtUnitS {
            get {
                return ResourceManager.GetString("txtUnitS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string txtUserLogin {
            get {
                return ResourceManager.GetString("txtUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи системы.
        /// </summary>
        public static string txtUserManagement {
            get {
                return ResourceManager.GetString("txtUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string txtUserName {
            get {
                return ResourceManager.GetString("txtUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи системы.
        /// </summary>
        public static string txtUsersSystem {
            get {
                return ResourceManager.GetString("txtUsersSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г..
        /// </summary>
        public static string txtY {
            get {
                return ResourceManager.GetString("txtY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м3.
        /// </summary>
        public static string unit_of_cargo_m3 {
            get {
                return ResourceManager.GetString("unit_of_cargo_m3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пассажиры.
        /// </summary>
        public static string unit_of_cargo_Passengers {
            get {
                return ResourceManager.GetString("unit_of_cargo_Passengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на т.
        /// </summary>
        public static string unit_of_cargo_t {
            get {
                return ResourceManager.GetString("unit_of_cargo_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на т-DWT.
        /// </summary>
        public static string unit_of_cargo_t_DWT {
            get {
                return ResourceManager.GetString("unit_of_cargo_t_DWT", resourceCulture);
            }
        }
    }
}
