//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesReplaced_Helicopter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesReplaced_Helicopter() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Properties.ResourcesReplaced_Helicopter", typeof(ResourcesReplaced_Helicopter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Монитор ВС.
        /// </summary>
        public static string fFleetMonitor {
            get {
                return ResourceManager.GetString("fFleetMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный документ будет удален на каждом ВС!
        ///Вы уверены, что хотите продолжить?.
        /// </summary>
        public static string mConfirmDelDocumentsAtAllVessels {
            get {
                return ResourceManager.GetString("mConfirmDelDocumentsAtAllVessels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить данное ВС вместе с его каталогом?.
        /// </summary>
        public static string mConfirmDelShip {
            get {
                return ResourceManager.GetString("mConfirmDelShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите удалить данный тип ВС?.
        /// </summary>
        public static string mConfirmDelShipType {
            get {
                return ResourceManager.GetString("mConfirmDelShipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно удалить данный тип ВС, так как есть связанные с ним ВС!.
        /// </summary>
        public static string mNotDelShipTypeBecauseHasShips {
            get {
                return ResourceManager.GetString("mNotDelShipTypeBecauseHasShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все вносимые изменения применяются ко всем ВС.
        /// </summary>
        public static string txtChangesAllShips {
            get {
                return ResourceManager.GetString("txtChangesAllShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать ВС, где будет скрываться документ.
        /// </summary>
        public static string txtChangeVesselForVisibleDoc {
            get {
                return ResourceManager.GetString("txtChangeVesselForVisibleDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите ВС, для которых необходимо скопировать счетчики.
        /// </summary>
        public static string txtChooseShipsForCountersCopy {
            get {
                return ResourceManager.GetString("txtChooseShipsForCountersCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtCommentForShip {
            get {
                return ResourceManager.GetString("txtCommentForShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создано ВС:.
        /// </summary>
        public static string txtCreatedByVessel {
            get {
                return ResourceManager.GetString("txtCreatedByVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создано ВС.
        /// </summary>
        public static string txtCreatedByVesselInfo {
            get {
                return ResourceManager.GetString("txtCreatedByVesselInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtCreateRecoverPackageText {
            get {
                return ResourceManager.GetString("txtCreateRecoverPackageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменено ВС:.
        /// </summary>
        public static string txtEditedByVessel {
            get {
                return ResourceManager.GetString("txtEditedByVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воздушный флот.
        /// </summary>
        public static string txtFleet {
            get {
                return ResourceManager.GetString("txtFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление воздушным флотом.
        /// </summary>
        public static string txtFleetManagement {
            get {
                return ResourceManager.GetString("txtFleetManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtForChangingVesselSheduler {
            get {
                return ResourceManager.GetString("txtForChangingVesselSheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtForFleet {
            get {
                return ResourceManager.GetString("txtForFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtForShip {
            get {
                return ResourceManager.GetString("txtForShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для просмотра данных выберите ВС..
        /// </summary>
        public static string txtForViewingDataForVessel {
            get {
                return ResourceManager.GetString("txtForViewingDataForVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtFuelTypeEmissionFactor {
            get {
                return ResourceManager.GetString("txtFuelTypeEmissionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtFuelTypeIsUseOnShip {
            get {
                return ResourceManager.GetString("txtFuelTypeIsUseOnShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtFuelTypeIsUseOnShipView {
            get {
                return ResourceManager.GetString("txtFuelTypeIsUseOnShipView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtFuelTypeName {
            get {
                return ResourceManager.GetString("txtFuelTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtFuelTypeShortName {
            get {
                return ResourceManager.GetString("txtFuelTypeShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IMO.
        /// </summary>
        public static string txtIMO {
            get {
                return ResourceManager.GetString("txtIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата выпуска.
        /// </summary>
        public static string txtIssueDate {
            get {
                return ResourceManager.GetString("txtIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtLastVesselExportDate {
            get {
                return ResourceManager.GetString("txtLastVesselExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О..
        /// </summary>
        public static string txtMasterName {
            get {
                return ResourceManager.GetString("txtMasterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подпись.
        /// </summary>
        public static string txtMasterSignature {
            get {
                return ResourceManager.GetString("txtMasterSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общие справочники воздушного флота.
        /// </summary>
        public static string txtMenuFleetDirectories {
            get {
                return ResourceManager.GetString("txtMenuFleetDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники BC.
        /// </summary>
        public static string txtMenuVesselDirectories {
            get {
                return ResourceManager.GetString("txtMenuVesselDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtModePeriodList {
            get {
                return ResourceManager.GetString("txtModePeriodList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активные.
        /// </summary>
        public static string txtOnBoard {
            get {
                return ResourceManager.GetString("txtOnBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ для ВС.
        /// </summary>
        public static string txtOrdersForVessels {
            get {
                return ResourceManager.GetString("txtOrdersForVessels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtRecoveringShipDB {
            get {
                return ResourceManager.GetString("txtRecoveringShipDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для некритических объектов процент невыполненных работ от запланированных работ по всем ВС:.
        /// </summary>
        public static string txtReportStatisticTotal1 {
            get {
                return ResourceManager.GetString("txtReportStatisticTotal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для критических объектов процент невыполненных работ от запланированных работ по всем ВС:.
        /// </summary>
        public static string txtReportStatisticTotal2 {
            get {
                return ResourceManager.GetString("txtReportStatisticTotal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общий процент невыполненных работ от запланированных работ по всем ВС:.
        /// </summary>
        public static string txtReportStatisticTotal3 {
            get {
                return ResourceManager.GetString("txtReportStatisticTotal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtRequisitionItemNumToolTip_Delivered {
            get {
                return ResourceManager.GetString("txtRequisitionItemNumToolTip_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtRequisitionItemNumToolTip_OrderByShip {
            get {
                return ResourceManager.GetString("txtRequisitionItemNumToolTip_OrderByShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtRequisitionItemsToolTip {
            get {
                return ResourceManager.GetString("txtRequisitionItemsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарезервировано для ВС.
        /// </summary>
        public static string txtReservedForVessel {
            get {
                return ResourceManager.GetString("txtReservedForVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резерв для ВС.
        /// </summary>
        public static string txtReserverForVessels {
            get {
                return ResourceManager.GetString("txtReserverForVessels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер каталога ВС.
        /// </summary>
        public static string txtRolePMSShipCatalogueManager {
            get {
                return ResourceManager.GetString("txtRolePMSShipCatalogueManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите ВС.
        /// </summary>
        public static string txtSelectVessel {
            get {
                return ResourceManager.GetString("txtSelectVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите ВС!.
        /// </summary>
        public static string txtSelectVesselMess {
            get {
                return ResourceManager.GetString("txtSelectVesselMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtShipFuelTypeListIsEmpty {
            get {
                return ResourceManager.GetString("txtShipFuelTypeListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа ВС.
        /// </summary>
        public static string txtShipGroup {
            get {
                return ResourceManager.GetString("txtShipGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Собственник.
        /// </summary>
        public static string txtShipowner {
            get {
                return ResourceManager.GetString("txtShipowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа ВС.
        /// </summary>
        public static string txtShipsGroup {
            get {
                return ResourceManager.GetString("txtShipsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группы ВС.
        /// </summary>
        public static string txtShipsGroups {
            get {
                return ResourceManager.GetString("txtShipsGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить судовые сертификаты для воздушного флота.
        /// </summary>
        public static string txtShowDocsByFleet {
            get {
                return ResourceManager.GetString("txtShowDocsByFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить заявки для воздушного флота.
        /// </summary>
        public static string txtShowReqForFleet {
            get {
                return ResourceManager.GetString("txtShowReqForFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комиссия составила и утвердила настоящий акт в том, что нижепоименованные СЗЧ и материалы были установлены, израсходованы и подлежат списанию..
        /// </summary>
        public static string txtSpareDeleteTextReport {
            get {
                return ResourceManager.GetString("txtSpareDeleteTextReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталоги ВС.
        /// </summary>
        public static string txtSpareLibTabVesselCat {
            get {
                return ResourceManager.GetString("txtSpareLibTabVesselCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раздел склада ВС.
        /// </summary>
        public static string txtStoreSectionVessel {
            get {
                return ResourceManager.GetString("txtStoreSectionVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtTableOfWorkArrangements {
            get {
                return ResourceManager.GetString("txtTableOfWorkArrangements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtUnitOfCargoTextForUser {
            get {
                return ResourceManager.GetString("txtUnitOfCargoTextForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВС.
        /// </summary>
        public static string txtVessel {
            get {
                return ResourceManager.GetString("txtVessel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог ВС.
        /// </summary>
        public static string txtVesselCatalogue {
            get {
                return ResourceManager.GetString("txtVesselCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtVesselChoiceForCopy {
            get {
                return ResourceManager.GetString("txtVesselChoiceForCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtVesselCountryFlag {
            get {
                return ResourceManager.GetString("txtVesselCountryFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление сертификатами ВС.
        /// </summary>
        public static string txtVesselDocManagement {
            get {
                return ResourceManager.GetString("txtVesselDocManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ---.
        /// </summary>
        public static string txtVesselExportDate {
            get {
                return ResourceManager.GetString("txtVesselExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название ВС.
        /// </summary>
        public static string txtVesselName {
            get {
                return ResourceManager.GetString("txtVesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название ВС:.
        /// </summary>
        public static string txtVesselNameLic {
            get {
                return ResourceManager.GetString("txtVesselNameLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип  ВС.
        /// </summary>
        public static string txtVesselType {
            get {
                return ResourceManager.GetString("txtVesselType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные типа  ВС.
        /// </summary>
        public static string txtVesselTypeData {
            get {
                return ResourceManager.GetString("txtVesselTypeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название типа  ВС.
        /// </summary>
        public static string txtVesselTypeName {
            get {
                return ResourceManager.GetString("txtVesselTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Типы  ВС.
        /// </summary>
        public static string txtVesselTypes {
            get {
                return ResourceManager.GetString("txtVesselTypes", resourceCulture);
            }
        }
    }
}
