//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стиль приложения.
        /// </summary>
        public static string fStyleSettings {
            get {
                return ResourceManager.GetString("fStyleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие не доступно. Проверьте системную дату на вашем компьютере..
        /// </summary>
        public static string mActionNotAvailable {
            get {
                return ResourceManager.GetString("mActionNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректно задан период!.
        /// </summary>
        public static string mErIncorrectInputDatePeriod {
            get {
                return ResourceManager.GetString("mErIncorrectInputDatePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл был успешно сохранён: &quot;{0}&quot;..
        /// </summary>
        public static string mFileDownloadOk {
            get {
                return ResourceManager.GetString("mFileDownloadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не загружен!.
        /// </summary>
        public static string mFileNotLoaded {
            get {
                return ResourceManager.GetString("mFileNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер загружаемого файла не должен превышать {0} Мбайт..
        /// </summary>
        public static string mFileSizeTooLarge {
            get {
                return ResourceManager.GetString("mFileSizeTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск не дал результатов.
        /// </summary>
        public static string mNoResultSearch {
            get {
                return ResourceManager.GetString("mNoResultSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование выполнено.
        /// </summary>
        public static string mOkCoping {
            get {
                return ResourceManager.GetString("mOkCoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перемещение выполнено.
        /// </summary>
        public static string mOkMoving {
            get {
                return ResourceManager.GetString("mOkMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, отправьте лог-файл техподдержке ({0})..
        /// </summary>
        public static string mSendLogFileToSupport {
            get {
                return ResourceManager.GetString("mSendLogFileToSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string txtAdd {
            get {
                return ResourceManager.GetString("txtAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить всех.
        /// </summary>
        public static string txtAddAll {
            get {
                return ResourceManager.GetString("txtAddAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить и выбрать.
        /// </summary>
        public static string txtAddAndSelect {
            get {
                return ResourceManager.GetString("txtAddAndSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительная информация.
        /// </summary>
        public static string txtAdditionalInfo {
            get {
                return ResourceManager.GetString("txtAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string txtAll {
            get {
                return ResourceManager.GetString("txtAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество отвеченных вопросов в разделе.
        /// </summary>
        public static string txtAnsInChapter {
            get {
                return ResourceManager.GetString("txtAnsInChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ.
        /// </summary>
        public static string txtAnswer {
            get {
                return ResourceManager.GetString("txtAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НП.
        /// </summary>
        public static string txtAnswer_NA {
            get {
                return ResourceManager.GetString("txtAnswer_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не применимо.
        /// </summary>
        public static string txtAnswer_NAToolTip {
            get {
                return ResourceManager.GetString("txtAnswer_NAToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string txtAnswer_No {
            get {
                return ResourceManager.GetString("txtAnswer_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НВ.
        /// </summary>
        public static string txtAnswer_NS {
            get {
                return ResourceManager.GetString("txtAnswer_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не видел.
        /// </summary>
        public static string txtAnswer_NSToolTip {
            get {
                return ResourceManager.GetString("txtAnswer_NSToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string txtAnswer_Yes {
            get {
                return ResourceManager.GetString("txtAnswer_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string txtAply {
            get {
                return ResourceManager.GetString("txtAply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Апреля.
        /// </summary>
        public static string txtApr {
            get {
                return ResourceManager.GetString("txtApr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Апрель.
        /// </summary>
        public static string txtAprilM {
            get {
                return ResourceManager.GetString("txtAprilM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Августа.
        /// </summary>
        public static string txtAug {
            get {
                return ResourceManager.GetString("txtAug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Август.
        /// </summary>
        public static string txtAugustM {
            get {
                return ResourceManager.GetString("txtAugustM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Большой.
        /// </summary>
        public static string txtBig {
            get {
                return ResourceManager.GetString("txtBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обзор....
        /// </summary>
        public static string txtBrowser {
            get {
                return ResourceManager.GetString("txtBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Календарь.
        /// </summary>
        public static string txtCalendar {
            get {
                return ResourceManager.GetString("txtCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string txtCancel {
            get {
                return ResourceManager.GetString("txtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить.
        /// </summary>
        public static string txtClear {
            get {
                return ResourceManager.GetString("txtClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string txtClose {
            get {
                return ResourceManager.GetString("txtClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыто.
        /// </summary>
        public static string txtClosed {
            get {
                return ResourceManager.GetString("txtClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания.
        /// </summary>
        public static string txtCompany {
            get {
                return ResourceManager.GetString("txtCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное совпадение.
        /// </summary>
        public static string txtCompleteAgreement {
            get {
                return ResourceManager.GetString("txtCompleteAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер компонентов.
        /// </summary>
        public static string txtComponentSize {
            get {
                return ResourceManager.GetString("txtComponentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим конструктора включен.
        /// </summary>
        public static string txtConstructorModeIsOn {
            get {
                return ResourceManager.GetString("txtConstructorModeIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        public static string txtContinue {
            get {
                return ResourceManager.GetString("txtContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать.
        /// </summary>
        public static string txtCopy {
            get {
                return ResourceManager.GetString("txtCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копирование....
        /// </summary>
        public static string txtCopyInProgress {
            get {
                return ResourceManager.GetString("txtCopyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создано:.
        /// </summary>
        public static string txtCreated {
            get {
                return ResourceManager.GetString("txtCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создано компанией.
        /// </summary>
        public static string txtCreatedByCompanyInfo {
            get {
                return ResourceManager.GetString("txtCreatedByCompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экипаж.
        /// </summary>
        public static string txtCrew {
            get {
                return ResourceManager.GetString("txtCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        public static string txtDate {
            get {
                return ResourceManager.GetString("txtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата с.
        /// </summary>
        public static string txtDateFrom {
            get {
                return ResourceManager.GetString("txtDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата по.
        /// </summary>
        public static string txtDateTo {
            get {
                return ResourceManager.GetString("txtDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декабря.
        /// </summary>
        public static string txtDec {
            get {
                return ResourceManager.GetString("txtDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декабрь.
        /// </summary>
        public static string txtDecemberM {
            get {
                return ResourceManager.GetString("txtDecemberM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string txtDelete {
            get {
                return ResourceManager.GetString("txtDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снять выделение.
        /// </summary>
        public static string txtDeselect {
            get {
                return ResourceManager.GetString("txtDeselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробная информация.
        /// </summary>
        public static string txtDetailedInformation {
            get {
                return ResourceManager.GetString("txtDetailedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отобразить данные.
        /// </summary>
        public static string txtDisplayData {
            get {
                return ResourceManager.GetString("txtDisplayData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать файл.
        /// </summary>
        public static string txtDownloadFile {
            get {
                return ResourceManager.GetString("txtDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать пакет.
        /// </summary>
        public static string txtDownloadPackage {
            get {
                return ResourceManager.GetString("txtDownloadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string txtEdit {
            get {
                return ResourceManager.GetString("txtEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для редактирования данных дважды щелкните по ячейке.
        /// </summary>
        public static string txtEditableCellTooltip {
            get {
                return ResourceManager.GetString("txtEditableCellTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести данные..
        /// </summary>
        public static string txtEnterData {
            get {
                return ResourceManager.GetString("txtEnterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести вещественное число..
        /// </summary>
        public static string txtEnterFloatData {
            get {
                return ResourceManager.GetString("txtEnterFloatData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести неотрицательное вещественное число..
        /// </summary>
        public static string txtEnterFloatDataNonNegative {
            get {
                return ResourceManager.GetString("txtEnterFloatDataNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести положительное вещественное число (число большее нуля)..
        /// </summary>
        public static string txtEnterFloatDataPositive {
            get {
                return ResourceManager.GetString("txtEnterFloatDataPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести целое число..
        /// </summary>
        public static string txtEnterIntData {
            get {
                return ResourceManager.GetString("txtEnterIntData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести целое число в диапазоне от {0} до {1}..
        /// </summary>
        public static string txtEnterIntDataInRange {
            get {
                return ResourceManager.GetString("txtEnterIntDataInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести значение больше чем {0}..
        /// </summary>
        public static string txtEnterMoreValue {
            get {
                return ResourceManager.GetString("txtEnterMoreValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести не менее {0} символов..
        /// </summary>
        public static string txtEnterNotLessData {
            get {
                return ResourceManager.GetString("txtEnterNotLessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести значение не меньшее {0}..
        /// </summary>
        public static string txtEnterNotLessValue {
            get {
                return ResourceManager.GetString("txtEnterNotLessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести не более {0} символов..
        /// </summary>
        public static string txtEnterNotMoreData {
            get {
                return ResourceManager.GetString("txtEnterNotMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести пароль..
        /// </summary>
        public static string txtEnterPass {
            get {
                return ResourceManager.GetString("txtEnterPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный подтверждающий пароль.
        /// </summary>
        public static string txtEnterPassRepeat {
            get {
                return ResourceManager.GetString("txtEnterPassRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развернуть.
        /// </summary>
        public static string txtExpand {
            get {
                return ResourceManager.GetString("txtExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата экспорта.
        /// </summary>
        public static string txtExportDate {
            get {
                return ResourceManager.GetString("txtExportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправлено.
        /// </summary>
        public static string txtExportStateSended {
            get {
                return ResourceManager.GetString("txtExportStateSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово к отправке.
        /// </summary>
        public static string txtExportStateSendReady {
            get {
                return ResourceManager.GetString("txtExportStateSendReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Февраля.
        /// </summary>
        public static string txtFeb {
            get {
                return ResourceManager.GetString("txtFeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Февраль.
        /// </summary>
        public static string txtFebruaryM {
            get {
                return ResourceManager.GetString("txtFebruaryM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл.
        /// </summary>
        public static string txtFile {
            get {
                return ResourceManager.GetString("txtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string txtFileDescription {
            get {
                return ResourceManager.GetString("txtFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат файла.
        /// </summary>
        public static string txtFileFormat {
            get {
                return ResourceManager.GetString("txtFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название файла.
        /// </summary>
        public static string txtFileName {
            get {
                return ResourceManager.GetString("txtFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файлы.
        /// </summary>
        public static string txtFiles {
            get {
                return ResourceManager.GetString("txtFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер файла.
        /// </summary>
        public static string txtFileSize {
            get {
                return ResourceManager.GetString("txtFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество файлов.
        /// </summary>
        public static string txtFilesNumber {
            get {
                return ResourceManager.GetString("txtFilesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтрация.
        /// </summary>
        public static string txtFiltration {
            get {
                return ResourceManager.GetString("txtFiltration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя (англ.).
        /// </summary>
        public static string txtFirstnameEN {
            get {
                return ResourceManager.GetString("txtFirstnameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя (рус.).
        /// </summary>
        public static string txtFirstnameRU {
            get {
                return ResourceManager.GetString("txtFirstnameRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Первая страница.
        /// </summary>
        public static string txtFirstPage {
            get {
                return ResourceManager.GetString("txtFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Флаг.
        /// </summary>
        public static string txtFlag {
            get {
                return ResourceManager.GetString("txtFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для просмотра данных выделите день в календаре..
        /// </summary>
        public static string txtForViewingDataSelectDay {
            get {
                return ResourceManager.GetString("txtForViewingDataSelectDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для просмотра данных выделите запись..
        /// </summary>
        public static string txtForViewingDataSelectRecord {
            get {
                return ResourceManager.GetString("txtForViewingDataSelectRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пт.
        /// </summary>
        public static string txtFri {
            get {
                return ResourceManager.GetString("txtFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на с.
        /// </summary>
        public static string txtFrom {
            get {
                return ResourceManager.GetString("txtFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt; Назад.
        /// </summary>
        public static string txtGoLast {
            get {
                return ResourceManager.GetString("txtGoLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дальше &gt;.
        /// </summary>
        public static string txtGoNext {
            get {
                return ResourceManager.GetString("txtGoNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часы.
        /// </summary>
        public static string txtHours {
            get {
                return ResourceManager.GetString("txtHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IMO#.
        /// </summary>
        public static string txtIMO {
            get {
                return ResourceManager.GetString("txtIMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID#.
        /// </summary>
        public static string txtItemID {
            get {
                return ResourceManager.GetString("txtItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Января.
        /// </summary>
        public static string txtJan {
            get {
                return ResourceManager.GetString("txtJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Январь.
        /// </summary>
        public static string txtJanuaryM {
            get {
                return ResourceManager.GetString("txtJanuaryM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июля.
        /// </summary>
        public static string txtJul {
            get {
                return ResourceManager.GetString("txtJul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июль.
        /// </summary>
        public static string txtJulyM {
            get {
                return ResourceManager.GetString("txtJulyM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июня.
        /// </summary>
        public static string txtJun {
            get {
                return ResourceManager.GetString("txtJun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июнь.
        /// </summary>
        public static string txtJuneM {
            get {
                return ResourceManager.GetString("txtJuneM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последняя страница.
        /// </summary>
        public static string txtLastPage {
            get {
                return ResourceManager.GetString("txtLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string txtLoad {
            get {
                return ResourceManager.GetString("txtLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка данных.
        /// </summary>
        public static string txtLoadingData {
            get {
                return ResourceManager.GetString("txtLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Марта.
        /// </summary>
        public static string txtMar {
            get {
                return ResourceManager.GetString("txtMar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Март.
        /// </summary>
        public static string txtMarchM {
            get {
                return ResourceManager.GetString("txtMarchM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пометить как непросмотренное.
        /// </summary>
        public static string txtMarkAsNotWatched {
            get {
                return ResourceManager.GetString("txtMarkAsNotWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мая.
        /// </summary>
        public static string txtMay {
            get {
                return ResourceManager.GetString("txtMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Май.
        /// </summary>
        public static string txtMayM {
            get {
                return ResourceManager.GetString("txtMayM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний.
        /// </summary>
        public static string txtMedium {
            get {
                return ResourceManager.GetString("txtMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стиль приложения.
        /// </summary>
        public static string txtMenuStyleSettings {
            get {
                return ResourceManager.GetString("txtMenuStyleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пн.
        /// </summary>
        public static string txtMon {
            get {
                return ResourceManager.GetString("txtMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Месяц.
        /// </summary>
        public static string txtMonth {
            get {
                return ResourceManager.GetString("txtMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить.
        /// </summary>
        public static string txtMove {
            get {
                return ResourceManager.GetString("txtMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить в историю.
        /// </summary>
        public static string txtMoveToHistory {
            get {
                return ResourceManager.GetString("txtMoveToHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N/A.
        /// </summary>
        public static string txtNA {
            get {
                return ResourceManager.GetString("txtNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ф.И.О..
        /// </summary>
        public static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -.
        /// </summary>
        public static string txtNaN {
            get {
                return ResourceManager.GetString("txtNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл!.
        /// </summary>
        public static string txtNeedSelectFile {
            get {
                return ResourceManager.GetString("txtNeedSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующая страница.
        /// </summary>
        public static string txtNextPage {
            get {
                return ResourceManager.GetString("txtNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string txtNo {
            get {
                return ResourceManager.GetString("txtNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет данных.
        /// </summary>
        public static string txtNoData {
            get {
                return ResourceManager.GetString("txtNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование (русский).
        /// </summary>
        public static string txtNomination {
            get {
                return ResourceManager.GetString("txtNomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование (английский).
        /// </summary>
        public static string txtNominationEng {
            get {
                return ResourceManager.GetString("txtNominationEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет записей.
        /// </summary>
        public static string txtNoRecords {
            get {
                return ResourceManager.GetString("txtNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неактивный.
        /// </summary>
        public static string txtNotActive {
            get {
                return ResourceManager.GetString("txtNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оповещать за (дней).
        /// </summary>
        public static string txtNotify {
            get {
                return ResourceManager.GetString("txtNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбрано.
        /// </summary>
        public static string txtNotSelected {
            get {
                return ResourceManager.GetString("txtNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указано.
        /// </summary>
        public static string txtNotSpecified {
            get {
                return ResourceManager.GetString("txtNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не просмотрено.
        /// </summary>
        public static string txtNotWatched {
            get {
                return ResourceManager.GetString("txtNotWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноября.
        /// </summary>
        public static string txtNov {
            get {
                return ResourceManager.GetString("txtNov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноябрь.
        /// </summary>
        public static string txtNovemberM {
            get {
                return ResourceManager.GetString("txtNovemberM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечание.
        /// </summary>
        public static string txtObservation {
            get {
                return ResourceManager.GetString("txtObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество замечаний в разделе.
        /// </summary>
        public static string txtObsInChapter {
            get {
                return ResourceManager.GetString("txtObsInChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Октября.
        /// </summary>
        public static string txtOct {
            get {
                return ResourceManager.GetString("txtOct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Октябрь.
        /// </summary>
        public static string txtOctoberM {
            get {
                return ResourceManager.GetString("txtOctoberM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        public static string txtOpen {
            get {
                return ResourceManager.GetString("txtOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть файл.
        /// </summary>
        public static string txtOpenFile {
            get {
                return ResourceManager.GetString("txtOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть папку.
        /// </summary>
        public static string txtOpenFolder {
            get {
                return ResourceManager.GetString("txtOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть печатную форму.
        /// </summary>
        public static string txtOpenFormPrinting {
            get {
                return ResourceManager.GetString("txtOpenFormPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть печатную форму для поставщика.
        /// </summary>
        public static string txtOpenFormPrintingForSupplier {
            get {
                return ResourceManager.GetString("txtOpenFormPrintingForSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество (англ.).
        /// </summary>
        public static string txtPatronymicEN {
            get {
                return ResourceManager.GetString("txtPatronymicEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество (рус.).
        /// </summary>
        public static string txtPatronymicRU {
            get {
                return ResourceManager.GetString("txtPatronymicRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период.
        /// </summary>
        public static string txtPeriod {
            get {
                return ResourceManager.GetString("txtPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт.
        /// </summary>
        public static string txtPort {
            get {
                return ResourceManager.GetString("txtPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущая страница.
        /// </summary>
        public static string txtPrevPage {
            get {
                return ResourceManager.GetString("txtPrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос.
        /// </summary>
        public static string txtQuestion {
            get {
                return ResourceManager.GetString("txtQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество вопросов в разделе.
        /// </summary>
        public static string txtQuestionsInChapter {
            get {
                return ResourceManager.GetString("txtQuestionsInChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово.
        /// </summary>
        public static string txtReady {
            get {
                return ResourceManager.GetString("txtReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string txtRefresh {
            get {
                return ResourceManager.GetString("txtRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить.
        /// </summary>
        public static string txtReset {
            get {
                return ResourceManager.GetString("txtReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сб.
        /// </summary>
        public static string txtSat {
            get {
                return ResourceManager.GetString("txtSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string txtSave {
            get {
                return ResourceManager.GetString("txtSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string txtSearch {
            get {
                return ResourceManager.GetString("txtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раздел.
        /// </summary>
        public static string txtSection {
            get {
                return ResourceManager.GetString("txtSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string txtSelect {
            get {
                return ResourceManager.GetString("txtSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выделить все.
        /// </summary>
        public static string txtSelectAll {
            get {
                return ResourceManager.GetString("txtSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать файл.
        /// </summary>
        public static string txtSelectFile {
            get {
                return ResourceManager.GetString("txtSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите из списка или введите новое значение.
        /// </summary>
        public static string txtSelectOrEnterNew {
            get {
                return ResourceManager.GetString("txtSelectOrEnterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сентября.
        /// </summary>
        public static string txtSep {
            get {
                return ResourceManager.GetString("txtSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сентябрь.
        /// </summary>
        public static string txtSeptemberM {
            get {
                return ResourceManager.GetString("txtSeptemberM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Судовладелец.
        /// </summary>
        public static string txtShipowner {
            get {
                return ResourceManager.GetString("txtShipowner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать данные.
        /// </summary>
        public static string txtShowData {
            get {
                return ResourceManager.GetString("txtShowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать отчет.
        /// </summary>
        public static string txtShowReport {
            get {
                return ResourceManager.GetString("txtShowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свернуть.
        /// </summary>
        public static string txtShrink {
            get {
                return ResourceManager.GetString("txtShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маленький.
        /// </summary>
        public static string txtSmall {
            get {
                return ResourceManager.GetString("txtSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на №.
        /// </summary>
        public static string txtSortNumber {
            get {
                return ResourceManager.GetString("txtSortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № (для сортировки).
        /// </summary>
        public static string txtSortNumberText {
            get {
                return ResourceManager.GetString("txtSortNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начните ввод....
        /// </summary>
        public static string txtStartTyping {
            get {
                return ResourceManager.GetString("txtStartTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вс.
        /// </summary>
        public static string txtSun {
            get {
                return ResourceManager.GetString("txtSun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия (англ.).
        /// </summary>
        public static string txtSurnameEN {
            get {
                return ResourceManager.GetString("txtSurnameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия (рус.).
        /// </summary>
        public static string txtSurnameRU {
            get {
                return ResourceManager.GetString("txtSurnameRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чт.
        /// </summary>
        public static string txtThurs {
            get {
                return ResourceManager.GetString("txtThurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по.
        /// </summary>
        public static string txtTo {
            get {
                return ResourceManager.GetString("txtTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сегодня.
        /// </summary>
        public static string txtToday {
            get {
                return ResourceManager.GetString("txtToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вт.
        /// </summary>
        public static string txtTues {
            get {
                return ResourceManager.GetString("txtTues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключить режим конструктора.
        /// </summary>
        public static string txtTurnOffConstructorMode {
            get {
                return ResourceManager.GetString("txtTurnOffConstructorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить режим конструктора.
        /// </summary>
        public static string txtTurnOnConstructorMode {
            get {
                return ResourceManager.GetString("txtTurnOnConstructorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определено.
        /// </summary>
        public static string txtUndefined {
            get {
                return ResourceManager.GetString("txtUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о судне.
        /// </summary>
        public static string txtVesselInfo {
            get {
                return ResourceManager.GetString("txtVesselInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотреть.
        /// </summary>
        public static string txtView {
            get {
                return ResourceManager.GetString("txtView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подождите....
        /// </summary>
        public static string txtWaiting {
            get {
                return ResourceManager.GetString("txtWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ср.
        /// </summary>
        public static string txtWed {
            get {
                return ResourceManager.GetString("txtWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неделя.
        /// </summary>
        public static string txtWeek {
            get {
                return ResourceManager.GetString("txtWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string txtYes {
            get {
                return ResourceManager.GetString("txtYes", resourceCulture);
            }
        }
    }
}
