//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesMainW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesMainW() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Properties.ResourcesMainW", typeof(ResourcesMainW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string fAboutForm {
            get {
                return ResourceManager.GetString("fAboutForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите выйти из программы?.
        /// </summary>
        public static string mCloseApplication {
            get {
                return ResourceManager.GetString("mCloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самостоятельная компания.
        /// </summary>
        public static string txtAboutAutoCompanyModule {
            get {
                return ResourceManager.GetString("txtAboutAutoCompanyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самостоятельное судно.
        /// </summary>
        public static string txtAboutAutoShipModule {
            get {
                return ResourceManager.GetString("txtAboutAutoShipModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компания {0} рада предложить 
        ///программный модуль.
        /// </summary>
        public static string txtAboutCompany {
            get {
                return ResourceManager.GetString("txtAboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модуль компании.
        /// </summary>
        public static string txtAboutCompanyModule {
            get {
                return ResourceManager.GetString("txtAboutCompanyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модуль комплекса MARINER.
        /// </summary>
        public static string txtAboutComplex {
            get {
                return ResourceManager.GetString("txtAboutComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С нами можно связаться:.
        /// </summary>
        public static string txtAboutContact {
            get {
                return ResourceManager.GetString("txtAboutContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на электронная почта:.
        /// </summary>
        public static string txtAboutEmail {
            get {
                return ResourceManager.GetString("txtAboutEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОТ РАЗРАБОТЧИКА ПРОГРАММЫ.
        /// </summary>
        public static string txtAboutFrom {
            get {
                return ResourceManager.GetString("txtAboutFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Судовой модуль.
        /// </summary>
        public static string txtAboutShipModule {
            get {
                return ResourceManager.GetString("txtAboutShipModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skype:.
        /// </summary>
        public static string txtAboutSkype {
            get {
                return ResourceManager.GetString("txtAboutSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на телефон тех. поддержки:.
        /// </summary>
        public static string txtAboutSupportTel {
            get {
                return ResourceManager.GetString("txtAboutSupportTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на телефон:.
        /// </summary>
        public static string txtAboutTel {
            get {
                return ResourceManager.GetString("txtAboutTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модуль терминала.
        /// </summary>
        public static string txtAboutTerminalModule {
            get {
                return ResourceManager.GetString("txtAboutTerminalModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на официальный сайт:.
        /// </summary>
        public static string txtAboutWeb {
            get {
                return ResourceManager.GetString("txtAboutWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будет доступно в следующей версии.
        /// </summary>
        public static string txtAvailableNextVersion {
            get {
                return ResourceManager.GetString("txtAvailableNextVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string txtMenuAbout {
            get {
                return ResourceManager.GetString("txtMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники компании.
        /// </summary>
        public static string txtMenuCompanyDirectories {
            get {
                return ResourceManager.GetString("txtMenuCompanyDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройка подключения к SQL Server.
        /// </summary>
        public static string txtMenuConnectionSettings {
            get {
                return ResourceManager.GetString("txtMenuConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обмен данными.
        /// </summary>
        public static string txtMenuDataExchange {
            get {
                return ResourceManager.GetString("txtMenuDataExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники.
        /// </summary>
        public static string txtMenuDirectories {
            get {
                return ResourceManager.GetString("txtMenuDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт.
        /// </summary>
        public static string txtMenuExport {
            get {
                return ResourceManager.GetString("txtMenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал экспорта.
        /// </summary>
        public static string txtMenuExportJournal {
            get {
                return ResourceManager.GetString("txtMenuExportJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь.
        /// </summary>
        public static string txtMenuHelp {
            get {
                return ResourceManager.GetString("txtMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт.
        /// </summary>
        public static string txtMenuImport {
            get {
                return ResourceManager.GetString("txtMenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал импорта.
        /// </summary>
        public static string txtMenuImportJournal {
            get {
                return ResourceManager.GetString("txtMenuImportJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string txtMenuLanguage {
            get {
                return ResourceManager.GetString("txtMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление базами данных.
        /// </summary>
        public static string txtMenuManageDB {
            get {
                return ResourceManager.GetString("txtMenuManageDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string txtMenuSettings {
            get {
                return ResourceManager.GetString("txtMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление баз данных.
        /// </summary>
        public static string txtMenuUpdateDB {
            get {
                return ResourceManager.GetString("txtMenuUpdateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководство пользователя.
        /// </summary>
        public static string txtMenuUserGuide {
            get {
                return ResourceManager.GetString("txtMenuUserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно прав для доступа.
        /// </summary>
        public static string txtNotAvailableCheckListForUserAccess {
            get {
                return ResourceManager.GetString("txtNotAvailableCheckListForUserAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша лицензия не позволяет использовать данный модуль. Если Вы хотите работать с модулем EQUIPAGE, необходимо обратиться по адресу support@softmarine.org..
        /// </summary>
        public static string txtNotAvailableEQUIPAGEModuleForLic {
            get {
                return ResourceManager.GetString("txtNotAvailableEQUIPAGEModuleForLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша лицензия не позволяет использовать данный модуль. Если Вы хотите работать с модулем ISM, необходимо обратиться по адресу support@softmarine.org..
        /// </summary>
        public static string txtNotAvailableHSEQModuleForLic {
            get {
                return ResourceManager.GetString("txtNotAvailableHSEQModuleForLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для данного модуля недоступно!.
        /// </summary>
        public static string txtNotAvailableModule {
            get {
                return ResourceManager.GetString("txtNotAvailableModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша лицензия не позволяет использовать данный модуль. Если Вы хотите работать с модулем MRV, необходимо обратиться по адресу support@softmarine.org..
        /// </summary>
        public static string txtNotAvailableMRVModuleForLic {
            get {
                return ResourceManager.GetString("txtNotAvailableMRVModuleForLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша лицензия не позволяет использовать данный модуль. Если Вы хотите работать с модулем PERSONAL, необходимо обратиться по адресу support@softmarine.org..
        /// </summary>
        public static string txtNotAvailablePERSONALModuleForLic {
            get {
                return ResourceManager.GetString("txtNotAvailablePERSONALModuleForLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша лицензия не позволяет использовать данный модуль. Если Вы хотите работать с модулем СУБ, необходимо обратиться по адресу support@softmarine.org..
        /// </summary>
        public static string txtNotAvailableSMSModuleForLic {
            get {
                return ResourceManager.GetString("txtNotAvailableSMSModuleForLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DYNAMICA.
        /// </summary>
        public static string txtProjNameDYNAMICA {
            get {
                return ResourceManager.GetString("txtProjNameDYNAMICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EQUIPAGE.
        /// </summary>
        public static string txtProjNameEQUIPAGE {
            get {
                return ResourceManager.GetString("txtProjNameEQUIPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление инспекциями
        ///(INSPECTIONS AND AUDITS).
        /// </summary>
        public static string txtProjNameIAA {
            get {
                return ResourceManager.GetString("txtProjNameIAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор отчетов инспекций
        ///(INSPECTIONS REPORTS EDITOR).
        /// </summary>
        public static string txtProjNameIRE {
            get {
                return ResourceManager.GetString("txtProjNameIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MARINOS.
        /// </summary>
        public static string txtProjNamePMS {
            get {
                return ResourceManager.GetString("txtProjNamePMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система оценки знаний судового персонала
        ///(SHIP PERSONNEL TRAINING SYSTEM).
        /// </summary>
        public static string txtProjNameSPTS {
            get {
                return ResourceManager.GetString("txtProjNameSPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление пользователями.
        /// </summary>
        public static string txtUserManagement {
            get {
                return ResourceManager.GetString("txtUserManagement", resourceCulture);
            }
        }
    }
}
